#pragma once

// The browser shell, OS-free (plan M3): tabs, history, the address bar,
// chrome painted through ThemeTokens, the page painted through a scrolled
// viewport, link hit-testing — everything a window needs except the window.
// The platform layer feeds it input and blits the frame it paints; the
// --script replay drives it headlessly the same way, so shell tests run on
// every OS in CI and chrome screenshots are byte-identical across them.
//
// Loads are synchronous and queued: a navigation is performed by tick(), so
// the caller can present the "loading" frame first. The event-loop
// integration of fetch arrives with the multi-process split (plan M8).

#include "core/Bitmap.h"
#include "net/Http.h"
#include "net/Url.h"
#include "platform/Input.h"
#include "ui/Theme.h"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace sashfold::ui {

// Where documents come from: the shell's loader goes through the fetch
// choke point with the session's cookie jar and cache; tests inject canned
// pages. This is also the seam a renderer-process boundary would cut at.
class Loader {
public:
    virtual ~Loader() = default;
    // `referrer` is already policy-shaped (empty = send none); bypass_cache
    // is a user reload.
    virtual net::FetchResult load(net::Url const& url, std::string const& referrer,
        bool bypass_cache)
        = 0;
};

struct HistoryEntry {
    net::Url url; // as navigated
    net::Url final_url; // where it landed: the base for relative links
    std::string title;
    std::vector<std::uint8_t> bytes; // the document itself: Back never refetches
    std::string content_type;
    int status = 0;
    bool from_cache = false;
    bool internal = false; // an error page or about: page generated by the shell
    std::string error; // the loader's error, when internal
    int scroll_y = 0;
};

struct ChromeLayout {
    Rect tab_strip;
    Rect toolbar;
    Rect content;
    Rect status;
    Rect back_button;
    Rect forward_button;
    Rect reload_button;
    Rect new_tab_button;
    Rect address;
    std::vector<Rect> tabs;
    std::vector<Rect> tab_close_buttons;
};

class Browser {
public:
    Browser(Loader& loader, Theme theme, int width, int height);
    ~Browser();
    Browser(Browser const&) = delete;
    Browser& operator=(Browser const&) = delete;

    void set_theme(Theme theme);
    Theme const& theme() const;
    // Where downloads land. Empty disables downloading: a response the
    // engine cannot render then shows the unsupported-content page instead.
    void set_downloads_directory(std::string directory);
    void resize(int width, int height);
    int width() const;
    int height() const;

    // --- Input, window coordinates ------------------------------------------
    void mouse_move(int x, int y);
    void mouse_down(int x, int y, int button); // 1 left, 2 middle, 3 right
    void mouse_up(int x, int y, int button);
    void wheel(int x, int y, int notches); // positive scrolls the content up
    void key_down(platform::KeyEvent const& key);
    void text_input(char32_t code_point);

    // --- Navigation ---------------------------------------------------------
    // Address-bar semantics: a URL, or a bare host that tries https first.
    void navigate(std::string const& typed);
    void open(net::Url const& url);
    void open_in_new_tab(net::Url const& url);
    void back();
    void forward();
    void reload();
    void new_tab();
    void close_tab(std::size_t index);
    void select_tab(std::size_t index);

    bool has_pending_load() const;
    // Performs one queued load; true when it did.
    bool tick();

    // --- Output -------------------------------------------------------------
    Bitmap const& frame(); // paints when something changed
    bool needs_paint() const;
    platform::Cursor cursor() const;
    std::string window_title() const;

    // --- Inspection (tests and --script) ------------------------------------
    std::size_t tab_count() const;
    std::size_t active_tab() const;
    net::Url const* current_url() const;
    HistoryEntry const* current_entry() const;
    bool can_go_back() const;
    bool can_go_forward() const;
    std::string const& address_text() const;
    bool address_focused() const;
    std::string status_text() const;
    std::string page_title() const;
    std::string page_text() const; // the laid-out text, runs joined by spaces
    int scroll_y() const;
    std::optional<net::Url> link_at(int x, int y) const;
    // The window-coordinate center of the first text run containing `text`.
    std::optional<std::pair<int, int>> find_text(std::string const& text) const;
    ChromeLayout chrome_layout() const;

private:
    struct Impl;
    std::unique_ptr<Impl> m_impl;
};

}
