#!/usr/bin/env bash
# Writes src/platform/linux/KeysymData.h from X11/keysymdef.h: the X keysym
# encoding is the vocabulary an xkb keymap names its keys in, and the comments
# beside each definition carry the Unicode code point a keysym types. Two
# tables come out — name → keysym (sorted by name, for the keymap parser) and
# keysym → code point (sorted by keysym, for typed text) — so the shell never
# needs a keysym library. Re-run when keysymdef.h gains entries.
set -euo pipefail
export LC_ALL=C
header="${1:-/usr/include/X11/keysymdef.h}"
out="$(dirname "$0")/../src/platform/linux/KeysymData.h"

names="$(awk '/^#define XK_/ { print substr($2, 4) " " $3 }' "$header" | sort -k1,1 -u)"
unicode="$(awk '
/^#define XK_/ {
    value = strtonum($3)
    if (value >= 0x20 && value <= 0x7e) next      # ASCII maps to itself
    if (value >= 0xa0 && value <= 0xff) next      # so does Latin-1
    if (value >= 0x1000000) next                  # and the U+ form
    if (match($0, /\/\* U\+[0-9A-Fa-f]+ /)) {
        printf "%s 0x%s\n", $3, substr($0, RSTART + 5, RLENGTH - 6)
    }
}' "$header" | sort -k1,1 -u)"

{
    echo "#pragma once"
    echo
    echo "// Generated by tools/gen-keysyms.sh from X11/keysymdef.h (The Open Group,"
    echo "// MIT/X11 licence). The X keysym encoding is the public vocabulary xkb"
    echo "// keymaps name their symbols in; nothing here is code."
    echo "//"
    echo "// keysym_names: every named keysym, sorted by name for binary search."
    echo "// keysym_code_points: keysyms that type a character but are not the"
    echo "// character's own number (ASCII and Latin-1 keysyms are; the U+ form is),"
    echo "// sorted by keysym."
    echo
    echo "#include <cstdint>"
    echo
    echo "namespace sashfold::platform::xkb::data {"
    echo
    echo "struct KeysymName {"
    echo "    char const* name;"
    echo "    std::uint32_t keysym;"
    echo "};"
    echo
    echo "struct KeysymCodePoint {"
    echo "    std::uint32_t keysym;"
    echo "    char32_t code_point;"
    echo "};"
    echo
    echo "inline constexpr KeysymName keysym_names[] = {"
    echo "$names" | awk '{ printf "    { \"%s\", %s },\n", $1, $2 }'
    echo "};"
    echo
    echo "inline constexpr KeysymCodePoint keysym_code_points[] = {"
    echo "$unicode" | awk '{ printf "    { %s, %s },\n", $1, $2 }'
    echo "};"
    echo
    echo "}"
} > "$out"
echo "wrote $out: $(echo "$names" | wc -l) names, $(echo "$unicode" | wc -l) code points"
