# Generates src/html/Entities.h from the WHATWG named character reference
# table (https://html.spec.whatwg.org/entities.json — a copy is kept beside
# this script so regeneration is hermetic). Dev-time tool: never ships.
#
#   pwsh tools/gen-entities.ps1
param(
    [string]$InputJson = "$PSScriptRoot/entities.json",
    [string]$OutputHeader = "$PSScriptRoot/../src/html/Entities.h"
)
$ErrorActionPreference = 'Stop'

# -AsHashtable: the table legitimately contains keys differing only by case
# (&DownArrow; vs &Downarrow;), which PSObject property bags reject.
$entities = Get-Content -Raw $InputJson | ConvertFrom-Json -AsHashtable
$rows = [System.Collections.Generic.List[string]]::new()
$longest = 0
$count = 0

foreach ($entry in $entities.GetEnumerator()) {
    $name = $entry.Key.Substring(1) # strip the leading '&'
    if ($name.Length -gt $longest) { $longest = $name.Length }
    $cps = $entry.Value['codepoints']
    $first = [int]$cps[0]
    $second = if ($cps.Count -gt 1) { [int]$cps[1] } else { 0 }
    $rows.Add(('    {{ "{0}", 0x{1:X}, 0x{2:X} }},' -f $name, $first, $second))
    $count++
}

$header = @"
// Generated by tools/gen-entities.ps1 from the WHATWG named character
// reference table (entities.json). Do not edit by hand.
//
// Names are stored without the leading '&'. Most include the trailing ';';
// the legacy set without it is subject to the attribute-context rule in the
// tokenizer's named-character-reference state. Entries appear in source
// order; the tokenizer sorts its own index at first use.
#pragma once

#include <cstddef>
#include <string_view>

namespace sashfold::html {

struct NamedEntity {
    std::string_view name;
    char32_t first;
    char32_t second; // 0 when the entity maps to a single code point
};

inline constexpr std::size_t longest_entity_name = $longest;

inline constexpr NamedEntity named_entities[$count] = {
$($rows -join "`n")
};

}
"@

Set-Content -Path $OutputHeader -Value $header -NoNewline -Encoding utf8NoBOM
Write-Host "wrote $OutputHeader ($count entities, longest name $longest)"
